legend:
  wall: "#"
  pellet: "."
  power_pellet: "o"
  empty: " "
  pacman_spawn: "P"
  ghost_spawns:
    blinky: "1"
    pinky: "2"
    inky: "3"
    clyde: "4"

tunnels:
  wrap_rows:
    - 14

ghost_house:
  bounds:
    top: 11
    left: 9
    bottom: 18
    right: 18
  exit:
    row: 8
    col: 12

grid:
  - "############################"
  - "#............##............#"
  - "#.####.#####.##.#####.####.#"
  - "#o####.#####.##.#####.####o#"
  - "#.####.#####.##.#####.####.#"
  - "#..........................#"
  - "#.####.##.########.##.####.#"
  - "#.####.##.########.##.####.#"
  - "#......##....##....##......#"
  - "######.##### ## #####.######"
  - "######.##### ## #####.######"
  - "######.##    1     ##.######"
  - "######.## ###  ### ##.######"
  - "######.## #      # ##.######"
  - "      .   # 3 2 4#   .      "
  - "######.## #      # ##.######"
  - "######.## ######## ##.######"
  - "######.##          ##.######"
  - "######.## ######## ##.######"
  - "######.## ######## ##.######"
  - "#............##............#"
  - "#.####.#####.##.#####.####.#"
  - "#.####.#####.##.#####.####.#"
  - "#o..##.......P........##..o#"
  - "###.##.##.########.##.##.###"
  - "###.##.##.########.##.##.###"
  - "#......##....##....##......#"
  - "#.##########.##.##########.#"
  - "#.##########.##.##########.#"
  - "#..........................#"
  - "############################"
